################################################################################
## Calibration arguments
################################################################################


################################################################################
## Data generation arguments
################################################################################

trigger-time=1249852257.0 
gaussian-noise=True
zero-noise=False

################################################################################
## Detector arguments
################################################################################

detectors=[H1, L1]
duration=8.0 
psd-dict={"H1": "/mnt/home/users/uib54_res/resh000464/noise_curves/T2500310-v2_O5a_strain_psd.txt", "L1": "/mnt/home/users/uib54_res/resh000464/noise_curves/T2500310-v2_O5a_strain_psd.txt"} 
sampling-frequency=2048
reference-frequency=20
minimum-frequency={'H1': 20, 'L1': 20, 'waveform':13.33}
maximum-frequency= {'H1': 896, 'L1': 896}

################################################################################
## Injection arguments
################################################################################

injection=True
injection-dict={'mass_1': xx, 'mass_2': xx, 'luminosity_distance': xx, 'a_1': xx, 'a_2': xx, 'tilt_1': xx, 'tilt_2': xx, 'phi_12': xx, 'phi_jl': xx, 'theta_jn': xx, 'psi': xx, 'phase': xx, 'geocent_time': xx, 'ra': xx, 'dec': xx, 'minimum_frequency': 20.0, 'reference_frequency': 20.0, 'image_type' : xx} 
injection-waveform-approximant=IMRPhenomXPNR
injection-frequency-domain-source-model=hanabi.lensing.waveform.strongly_lensed_BBH_waveform
injection-waveform-arguments={'reference_frequency': 20, 'minimum_frequency': 20, 'pn_amplitude_order': 0}

################################################################################
## Job submission arguments
################################################################################

label=lenskyloc_inj_xxx_hanabi_single_imgx
outdir=injxxx/injxxx_imgx
request-disk=6.0
request-memory=110.0
request-memory-generation=2.0
request-cpus=128
scheduler=slurm
scheduler-args=constraint=cal
extra-lines=export MPLCONFIGDIR=$LOCALSCRATCH/$USER
scheduler-analysis-time=48:00:00

################################################################################
## Likelihood arguments
################################################################################


################################################################################
## Output arguments
################################################################################

result-format=json

################################################################################
## Prior arguments
################################################################################

prior-dict={chirp-mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=20.0, maximum=30.0, name='chirp_mass', boundary=None), mass-ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.05, maximum=1.0, name='mass_ratio', latex_label='$q$', unit=None, boundary=None), mass-1: Constraint(minimum=5.0, maximum=200.0, name='mass_1', latex_label='$m_1$', unit=None), mass-2: Constraint(minimum=5.0, maximum=200, name='mass_2', latex_label='$m_2$', unit=None), a-1: Uniform(minimum=0, maximum=0.99, name='a_1', latex_label='$a_1$', unit=None, boundary=None), a-2: Uniform(minimum=0, maximum=0.99, name='a_2', latex_label='$a_2$', unit=None, boundary=None), tilt-1: Sine(minimum=0, maximum=3.141592653589793, name='tilt_1'), tilt-2: Sine(minimum=0, maximum=3.141592653589793, name='tilt_2'), phi-12: Uniform(minimum=0, maximum=6.283185307179586, name='phi_12', boundary='periodic'), phi-jl: Uniform(minimum=0, maximum=6.283185307179586, name='phi_jl', boundary='periodic'), luminosity-distance: Uniform(minimum=50, maximum=20000, name='luminosity_distance', latex_label='$d_L$', unit='Mpc', boundary=None), cos-theta-jn: Uniform(minimum=-1, maximum=1, name='cos_theta_jn', latex_label='$\\cos\\theta_{JN}$', unit=None, boundary=None), psi: Uniform(minimum=0, maximum=3.141592653589793, name='psi', boundary='periodic'), phase: Uniform(minimum=0, maximum=6.283185307179586, name='phase', boundary='periodic'), dec: Cosine(minimum=-1.5707963267948966, maximum=1.5707963267948966, name='dec', latex_label='$\\mathrm{DEC}$', unit=None, boundary=None), ra: Uniform(minimum=0, maximum=6.283185307179586, name='ra', latex_label='$\\mathrm{RA}$', unit=None, boundary='periodic'),image_type = 1.0}  

################################################################################
## Post processing arguments
################################################################################


################################################################################
## Sampler arguments
################################################################################

n-parallel=3
sampler-kwargs={'nlive': 1000, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'samples': 'acceptance-walk', 'npool': 128}
distance_marginalization=False
time-marginalization=False
phase-marginalization=False


################################################################################
## Waveform arguments (used for the analysis)
################################################################################

waveform-generator=bilby.gw.waveform_generator.WaveformGenerator
frequency-domain-source-model=hanabi.lensing.waveform.strongly_lensed_BBH_waveform
waveform-approximant=IMRPhenomXPNR
enforce-signal-duration=False
catch-waveform-errors=True
pn-amplitude-order=1
