################################################################################
## Job submission arguments
################################################################################

label=lenskyloc_inj_123_hanabi_joint
outdir=injxxx/injxxx_joint
request-disk=6.0
request-memory=180.0 
request-memory-generation=2.0
request-cpus=128
scheduler=slurm
scheduler-args=constraint=cal
extra-lines=export MPLCONFIGDIR=$LOCALSCRATCH/$USER
scheduler-analysis-time=71:30:00

################################################################################
## Output arguments
################################################################################

result-format=json

################################################################################
## Post processing arguments
################################################################################


################################################################################
## Sampler arguments
################################################################################

sampler=dynesty
n-parallel=1
sampler-kwargs={'nlive': 1000, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'samples': 'acceptance-walk', 'npool': 128}

################################################################################
## Joint input arguments
################################################################################

n-triggers=2
trigger-ini-files=[/mnt/home/users/uib54_res/resh000464/lenskyloc/inj001/single_event_001_image1.ini, /mnt/home/users/uib54_res/resh000464/lenskyloc/inj001/single_event_001_image2.ini]

################################################################################
## Lensing prior argument
################################################################################

common-parameters=[chirp_mass, mass_ratio, mass_1, mass_2, a_1, a_2, tilt_1, tilt_2, phi_12, phi_jl, cos_theta_jn, ra, dec, psi, phase]
lensing-prior-dict={relative-magnification^(1): 1, image_type^(1) = hanabi.lensing.prior.DiscreteUniform(name='image_type^(1)', minimum=1, N=3), relative_magnification^(2) = 1, image_type^(2) = hanabi.lensing.prior.DiscreteUniform(name='image_type^(2)', minimum=1, N=3)}

################################################################################
## Waveform arguments
################################################################################
